export {default as Form_Login} from './Login/Form_Login'
export {default as Form_Register} from './Register/Form_Register'
export {default as Navbar } from './Navegación/Navbar/Navbar'
export {default as SideBar} from './Admin_Encuestas/SideBar/SideBar'
export {default as AdmCard} from './Admin_Encuestas/Card/AdmCard'
export {default as AdmGridCards} from './Admin_Encuestas/GridCards/AdmGridCards'
export {default as TypeText} from './Admin_Encuestas/CardContent/TypeText/TypeText'
export {default as TypeQuestion} from './Admin_Encuestas/CardContent/TypeQuestion/TypeQuestion'
export {default as TypeMultimedia} from './Admin_Encuestas/CardContent/TypeMultimedia/TypeMultimedia'
